name: LaTeX Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup TeXLive
      uses: docker://danteev/texlive
    - name: Build LaTeX document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error Report/main.tex
        rm -f *.aux *.log
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update PDF file"
